apiVersion: v1
kind: Service
metadata:
  name: postgres-external-service
  namespace: development
spec:
  selector:
    app: postgres
  type: LoadBalancer
  loadBalancerIP: 10.152.1.2
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432