apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: development
type: Opaque
data:
  postgres-admin-username: cG9zdGdyZXMtYWRtaW4=
  postgres-admin-password: OWQzYWRmZWZiN2ZkNDQ1ODhiNzY3YzZhODZhZGMzYWE=